### ISSUE TITLE
date issue

### ISSUE THREAD

**Issue by mousumidebtanwi** [Esri/drought-tracker#2]
graph and selected shows till feb 2019 instead of march 2021 when I run the demo code

**Comment by ChrisMahlke** [comment]
Can you provide more details on the issue?  Not sure what you mean by, "run the demo code"

**Comment by mousumidebtanwi** [comment]
I downloaded the github code in my local machine and browse the index.html and I noticed when I select a area its showing graph until feb 25 2019 instead of march 15 2021. However, in the live version https://livingatlas.arcgis.com/drought/ showing the correct graph. Is the live version is different than the github code. thank you so much for your reply. 
I am pasting here the graph I am getting.
![drought_tracker](https://user-images.githubusercontent.com/80921135/111880398-4c5acf80-8979-11eb-9e7b-bd4cdb6dd42b.png)

**Comment by ChrisMahlke** [comment]
@mousumidebtanwi Good catch...should be fine now.  I have updated the config file.

**Comment by mousumidebtanwi** [comment]
Thank you so much for your reply. I downloaded the updated config file tried again and still its showing graph until feb 25 2019 instead of march 15 2021.
![image](https://user-images.githubusercontent.com/80921135/111943981-a1473480-8aa4-11eb-9880-010b223d1cd2.png)

**Comment by ChrisMahlke** [comment]
@mousumidebtanwi Did you make sure to clear your cache?  That is the only file that has changed over the years and you have a copy of the file that is on production.

**Comment by mousumidebtanwi** [comment]
I did make sure to clear cache of my browser and checked again and did not get the luck.

**Comment by ChrisMahlke** [comment]
> I did make sure to clear cache of my browser and checked again and did not get the luck.

I pushed an update.  Can you please download the repo again and try it in your browser using Private mode?  Make sure the index.html is not modified.   Please reach out to me directly about updates to the application: cmahlke@esri.com

Thank you again for catching this.

![tmp](https://user-images.githubusercontent.com/4925379/112045812-80182f80-8b08-11eb-8054-1e1ade96758b.jpeg)
